version: '3.8'
services:
  mongo:
    image: mongo
    networks:
      - webapp-network
    restart: always
    command: '--logpath=/dev/null'
  myapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_PROD_URI=mongodb://mongo:27017/node-restful-prod
      - DB_DEV_URI=mongodb://mongo:27017/node-restful-dev
      - DB_TEST_URI=mongodb://mongo:27017/node-restful-test
    networks:
      - webapp-network
    depends_on:
      - mongo
    image: node-restful-api-shop:latest
    command: test_docker

networks:
  webapp-network:
    driver: bridge
