version: '3.8'
services:
  mongo:
    image: mongo
    networks:
      - webapp-network
    restart: always
    command: '--logpath=/dev/null'
  myapp:
    image: node-restful-api-shop:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
       - "127.0.0.1:3000:3000"
    environment:
      - DB_PROD_URI=mongodb://mongo:27017/node-restful-prod
      - DB_DEV_URI=mongodb://mongo:27017/node-restful-dev
      - DB_TEST_URI=mongodb://mongo:27017/node-restful-test
    networks:
      - webapp-network
    depends_on:
      - mongo
  
    command: ["./wait-for-it.sh", "mongo:27017", "--", "npm", "run", "start"]

networks:
  webapp-network:
    driver: bridge
